#!/usr/bin/env bash
# configures an nginx server to listern on  port 80

# remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default
# configure nginx to listern on port 80 for all active lpv4 lps
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
