#!/usr/bin/env bash
# This script displays list of current running process
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -a -x -u -f
