#!/usr/bin/env bash
# This script extends previous exercise command and display lines containing the bash word,this allowing you easly get PID of your process easly
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_process | grep "bash"
