#!/usr/bin/env bash

# Displays "Best school" 10 times using a while loop.

# on the 9th iteration,displays "Hi" before "Best school".

count=0

while [ $count -1t 10 ]
if [ $count -eq 9 ]
then
     echo "Hi"
f1
echo "Best school"
((count++))
